In [1]:
mylist = [1, 2, 3]
mylist.append(4)

In [2]:
import numpy as np

In [11]:
import importlib

In [5]:
myar =  np.append(mylist, 5)

In [ ]:
# ok, np.append returns the modified list as array

In [6]:
np.exp(-myar)

array([0.36787944, 0.13533528, 0.04978707, 0.01831564, 0.00673795])

In [3]:
import MLP

In [39]:
importlib.reload(MLP)

<module 'MLP' from '/workspaces/training-neural-networks-in-python-3215347/src/MLP.py'>

In [8]:
p = MLP.Perceptron(5)

In [9]:
p.bias

1.0

In [10]:
p.run([1, 2, 3, 4, 5])

0.21601333413514975

In [16]:
def test_perceptron(weights):
  """
  weights: weights for the inputs + bias
  """
  p = MLP.Perceptron(len(weights) - 1)
  p.set_weights(weights)
  # field width
  w = 10
  for A in (0, 1):
    for B in (0, 1):
      print(f"{A} {B}\t{weights[0]} {weights[1]}\t{p.weighted_sum([A, B])}\t{p.run([A, B])}")
  


In [17]:
test_perceptron([10, 10, -15]) # AND gate

0 0	10 10	-15.0	3.059022269256247e-07
0 1	10 10	-5.0	0.0066928509242848554
1 0	10 10	-5.0	0.0066928509242848554
1 1	10 10	5.0	0.9933071490757153


In [18]:
test_perceptron([10, 10, -5])  # OR gate


0 0	10 10	-5.0	0.0066928509242848554
0 1	10 10	5.0	0.9933071490757153
1 0	10 10	5.0	0.9933071490757153
1 1	10 10	15.0	0.999999694097773


In [19]:
test_perceptron([-10, -10, 15])  # NAND gate


0 0	-10 -10	15.0	0.999999694097773
0 1	-10 -10	5.0	0.9933071490757153
1 0	-10 -10	5.0	0.9933071490757153
1 1	-10 -10	-5.0	0.0066928509242848554


In [22]:
test_perceptron([-10, -10, 5])  # NOR gate


0 0	-10 -10	5.0	0.9933071490757153
0 1	-10 -10	-5.0	0.0066928509242848554
1 0	-10 -10	-5.0	0.0066928509242848554
1 1	-10 -10	-15.0	3.059022269256247e-07


In [32]:

or_gate = MLP.Perceptron(2)
or_gate.set_weights([10, 10, -5])
nand_gate = MLP.Perceptron(2)
nand_gate.set_weights([-10, -10, 15])

class Xor_gate():
  def __init__(self):
    self.or_gate = MLP.Perceptron(2)
    self.or_gate.set_weights([10, 10, -5])
    self.nand_gate = MLP.Perceptron(2)
    self.nand_gate.set_weights([-10, -10, 15])
    self.and_gate = MLP.Perceptron(2)
    self.and_gate.set_weights([10, 10, -15])

  def run(self, x):
    #or_out = self.or_gate.run(x)
    #nand_out = self.nand_gate.run(x)
    #return np.logical_and(*[np.round(y) for y in (or_out, nand_out)])
    return self.and_gate.run([self.or_gate.run(x), self.nand_gate.run(x)])
  


In [33]:
xor = Xor_gate()

In [34]:
xor.run([0, 0])

0.0071527881888964855

In [35]:
xor.run([0, 1])


0.9923558641717396

In [36]:
xor.run([1, 0])


0.9923558641717396

In [37]:
xor.run([1, 1])

0.0071527881888964855

In [26]:
import importlib
importlib.reload(MLP)

<module 'MLP' from '/workspaces/training-neural-networks-in-python-3215347/src/MLP.py'>

In [27]:
# testing MLP as given, first is number of inputs, 
# the rest number of neurons in each layer
mlp = MLP.MultiLayerPerceptron([2, 2, 1])

In [18]:
mlp.layers

array([2, 2, 1], dtype=object)

In [19]:
mlp.network

array([array([], dtype=float64),
       array([<MLP.Perceptron object at 0x7f452c5578b0>,
              <MLP.Perceptron object at 0x7f452c557700>], dtype=object),
       array([<MLP.Perceptron object at 0x7f452c5576a0>], dtype=object)],
      dtype=object)

In [20]:
mlp.print_weights()


Layer 2 Neuron 0 [-0.47314802 -0.85040192  0.68775855]
Layer 2 Neuron 1 [-0.59177123  0.62718073  0.32595968]
Layer 3 Neuron 0 [ 0.90351278 -0.24974126 -0.22473417]



In [28]:
mlp.set_weights([[[10, 10, -5], [-10, -10, 15]], [[10, 10, -15]]])


In [29]:
mlp.print_weights()


Layer 2 Neuron 0 [10 10 -5]
Layer 2 Neuron 1 [-10 -10  15]
Layer 3 Neuron 0 [ 10  10 -15]



In [30]:
mlp.values

array([array([0., 0.]), array([0., 0.]), array([0.])], dtype=object)

In [31]:
mlp.run([0, 0])

array([0.00715279])

In [32]:
mlp.run([1, 0])


array([0.99235586])

In [33]:
mlp.run([0, 1])

array([0.99235586])

In [34]:
mlp.run([1, 1])


array([0.00715279])

Bad pipe message: %s [b"\xf5\x80\x06\xcc,'\xe6 \xe0\x8e\x14\xbd\xf8\x0eV\xcb\x89w Nz\xf1yy\xd5\xc9\xfc6\xc8\xbd~\xb8\xd0\xde\xa1\x9a\xd5KK\xf3 `\xdfI_\xff\x80\x878\xe21\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\t12"]
Bad pipe message: %s [b'0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x00\x1e\x00\x1c\x04\x03\x05\x03\x06\x03\x08']
Bad pipe message: %s [b'\xe6/\x07\xfd\xf1\xf5xHw_\x04\xe2\x11\x0e\t\xd8[3\x00\x00>\xc0\x14\xc0\n\x009\x008\x007\x006\xc0\x0f\xc0\x05\x005\xc0\x13\xc0\t\x003\x002\x001\x00', b'\x0e\xc0\x04\x00/\x00\x9a\x00\x99\x00\x98\x00\x97\x00\x96\x00\x07\xc0\x11\xc0\x07\xc0\x0c\xc0\x02\x00\x05\x00\x04\x00\xff\x02\x01\x00\x00C\x00\x00\x00\x0e\x00\x0c\x00\x00\t12']
Bad pipe message: %s [b"\x0b\xddO\xe4\xb1\x9f\x99j3\r1'\xf4\x19I^9 \x00\x00>\xc0\x14\xc0\n\x009\x008\x007\x006\xc0\x0f\xc0\x05\x005\xc0\x13\xc0\t\x003\x002\x001\x000\

In [40]:
np.sum(np.square(mlp.values[-2]))

1.0000441824491344

In [38]:
import numpy as np

In [41]:
list(reversed(range(1,len(mlp.network)-1)))

[1]

In [42]:
list(reversed(range(1, 5-1)))

[3, 2, 1]